name: Build

on:
  workflow_dispatch:

jobs:
  test-windows:
    name: Test Windows build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Windows

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Test
        run: .\setup.ps1
